#!/bin/bash

total=0
successes=0

echo " "
echo -e "\e[32mRunning pre-commit checks...\e[0m"

run() {
  (( total++ ))
  local command="$1"

  echo " "
  echo -e "\e[32mRunning: $command\e[0m"

  if ( yarn $command ); then
    (( successes += 1 ))
  else
    echo -e "\e[31m✘ $command failed\e[0m"
  fi
}

run lint
run typecheck
run test
rm -rf .test
run build

echo " "

if ( [ $successes -eq $total ] ); then
  echo -e "\e[32m✔ All commands succeeded, ready to commit!\e[0m"
else
  echo -e "\e[31m✘ Some commands failed\e[0m"
  exit 1
fi
